services:
  qdrant:
    image: qdrant/qdrant:latest  # Or :latest â€” but pin for reproducibility
    container_name: qdrant
    ports:
      - "6333:6333"       # REST + gRPC
      - "6334:6334"       # Optional dashboard if enabled
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  app:
    build: .
    container_name: rag-app
    ports:
      - "8000:8000"
    env_file:
      - .env               # Your OPENAI_API_KEY etc.
    depends_on:
      - qdrant
      - redis
    volumes:
      - .:/app             # For hot-reload in dev (optional: remove in prod)
      # - hf_cache:/home/appuser/.cache/huggingface
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]  # In PROD, remove "--reload" and "uv run" (use the system python)

  eval:
    build: .
    container_name: rag-eval
    profiles:
      - ignore_on_up  # <--- Name this whatever you want
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app  # Look in /app for any modules I try to import.
    depends_on:
      - qdrant
      - redis
    volumes:
      - .:/app             # For hot-reload in dev (optional: remove in prod)
    command: ["uv", "run", "python", "-m", "app.evaluation.run_eval"]

volumes:
  qdrant_data:
  redis_data:
  # hf_cache: